services:
  # Commercify API service for local development with SQLite
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: commercify-api-local
    env_file:
      - .env.local
    environment:
      DB_DRIVER: sqlite
      DB_NAME: /app/data/commercify.db
    ports:
      - "6091:6091"
    volumes:
      # Mount a volume for SQLite database persistence
      - sqlite_data:/app/data
    restart: unless-stopped

  seed:
    build:
      context: .
      dockerfile: Dockerfile
    profiles: ["tools"]
    entrypoint: ["/app/commercify-seed"]
    command: ["-all"]
    environment:
      DB_DRIVER: sqlite
      DB_NAME: /app/data/commercify.db
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
