// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: api/orders.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus_Status int32

const (
	OrderStatus_PENDING   OrderStatus_Status = 0
	OrderStatus_PAID      OrderStatus_Status = 1
	OrderStatus_SHIPPED   OrderStatus_Status = 2
	OrderStatus_COMPLETED OrderStatus_Status = 3
	OrderStatus_RETURNED  OrderStatus_Status = 4
	OrderStatus_CANCELLED OrderStatus_Status = 5
	OrderStatus_FAILED    OrderStatus_Status = 6
)

// Enum value maps for OrderStatus_Status.
var (
	OrderStatus_Status_name = map[int32]string{
		0: "PENDING",
		1: "PAID",
		2: "SHIPPED",
		3: "COMPLETED",
		4: "RETURNED",
		5: "CANCELLED",
		6: "FAILED",
	}
	OrderStatus_Status_value = map[string]int32{
		"PENDING":   0,
		"PAID":      1,
		"SHIPPED":   2,
		"COMPLETED": 3,
		"RETURNED":  4,
		"CANCELLED": 5,
		"FAILED":    6,
	}
)

func (x OrderStatus_Status) Enum() *OrderStatus_Status {
	p := new(OrderStatus_Status)
	*p = x
	return p
}

func (x OrderStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_orders_proto_enumTypes[0].Descriptor()
}

func (OrderStatus_Status) Type() protoreflect.EnumType {
	return &file_api_orders_proto_enumTypes[0]
}

func (x OrderStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus_Status.Descriptor instead.
func (OrderStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_orders_proto_rawDescGZIP(), []int{2, 0}
}

type GetOrderQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderQuery) Reset() {
	*x = GetOrderQuery{}
	mi := &file_api_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderQuery) ProtoMessage() {}

func (x *GetOrderQuery) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderQuery.ProtoReflect.Descriptor instead.
func (*GetOrderQuery) Descriptor() ([]byte, []int) {
	return file_api_orders_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrderQuery) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResult) Reset() {
	*x = GetOrderResult{}
	mi := &file_api_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResult) ProtoMessage() {}

func (x *GetOrderResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResult.ProtoReflect.Descriptor instead.
func (*GetOrderResult) Descriptor() ([]byte, []int) {
	return file_api_orders_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderResult) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrderResult) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type OrderStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        OrderStatus_Status     `protobuf:"varint,1,opt,name=status,proto3,enum=api.OrderStatus_Status" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatus) Reset() {
	*x = OrderStatus{}
	mi := &file_api_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatus) ProtoMessage() {}

func (x *OrderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatus.ProtoReflect.Descriptor instead.
func (*OrderStatus) Descriptor() ([]byte, []int) {
	return file_api_orders_proto_rawDescGZIP(), []int{2}
}

func (x *OrderStatus) GetStatus() OrderStatus_Status {
	if x != nil {
		return x.Status
	}
	return OrderStatus_PENDING
}

func (x *OrderStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateOrderCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderCommand) Reset() {
	*x = CreateOrderCommand{}
	mi := &file_api_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderCommand) ProtoMessage() {}

func (x *CreateOrderCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderCommand.ProtoReflect.Descriptor instead.
func (*CreateOrderCommand) Descriptor() ([]byte, []int) {
	return file_api_orders_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderCommand) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateOrderCommand) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateOrderResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResult) Reset() {
	*x = CreateOrderResult{}
	mi := &file_api_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResult) ProtoMessage() {}

func (x *CreateOrderResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResult.ProtoReflect.Descriptor instead.
func (*CreateOrderResult) Descriptor() ([]byte, []int) {
	return file_api_orders_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrderResult) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PriceId       string                 `protobuf:"bytes,4,opt,name=price_id,json=priceId,proto3" json:"price_id,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_api_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_api_orders_proto_rawDescGZIP(), []int{5}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetPriceId() string {
	if x != nil {
		return x.PriceId
	}
	return ""
}

func (x *OrderItem) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_api_orders_proto protoreflect.FileDescriptor

const file_api_orders_proto_rawDesc = "" +
	"\n" +
	"\x10api/orders.proto\x12\x03api\"*\n" +
	"\rGetOrderQuery\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"i\n" +
	"\x0eGetOrderResult\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12$\n" +
	"\x05items\x18\x03 \x03(\v2\x0e.api.OrderItemR\x05items\"\xbe\x01\n" +
	"\vOrderStatus\x12/\n" +
	"\x06status\x18\x01 \x01(\x0e2\x17.api.OrderStatus.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"d\n" +
	"\x06Status\x12\v\n" +
	"\aPENDING\x10\x00\x12\b\n" +
	"\x04PAID\x10\x01\x12\v\n" +
	"\aSHIPPED\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\f\n" +
	"\bRETURNED\x10\x04\x12\r\n" +
	"\tCANCELLED\x10\x05\x12\n" +
	"\n" +
	"\x06FAILED\x10\x06\"[\n" +
	"\x12CreateOrderCommand\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12$\n" +
	"\x05items\x18\x02 \x03(\v2\x0e.api.OrderItemR\x05items\"F\n" +
	"\x11CreateOrderResult\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xa0\x01\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x19\n" +
	"\bprice_id\x18\x04 \x01(\tR\apriceId\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency2\x83\x01\n" +
	"\fOrderService\x12>\n" +
	"\vCreateOrder\x12\x17.api.CreateOrderCommand\x1a\x16.api.CreateOrderResult\x123\n" +
	"\bGetOrder\x12\x12.api.GetOrderQuery\x1a\x13.api.GetOrderResultB-Z+github.com/zenfulcode/commercify/common/apib\x06proto3"

var (
	file_api_orders_proto_rawDescOnce sync.Once
	file_api_orders_proto_rawDescData []byte
)

func file_api_orders_proto_rawDescGZIP() []byte {
	file_api_orders_proto_rawDescOnce.Do(func() {
		file_api_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_orders_proto_rawDesc), len(file_api_orders_proto_rawDesc)))
	})
	return file_api_orders_proto_rawDescData
}

var file_api_orders_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_orders_proto_goTypes = []any{
	(OrderStatus_Status)(0),    // 0: api.OrderStatus.Status
	(*GetOrderQuery)(nil),      // 1: api.GetOrderQuery
	(*GetOrderResult)(nil),     // 2: api.GetOrderResult
	(*OrderStatus)(nil),        // 3: api.OrderStatus
	(*CreateOrderCommand)(nil), // 4: api.CreateOrderCommand
	(*CreateOrderResult)(nil),  // 5: api.CreateOrderResult
	(*OrderItem)(nil),          // 6: api.OrderItem
}
var file_api_orders_proto_depIdxs = []int32{
	6, // 0: api.GetOrderResult.items:type_name -> api.OrderItem
	0, // 1: api.OrderStatus.status:type_name -> api.OrderStatus.Status
	6, // 2: api.CreateOrderCommand.items:type_name -> api.OrderItem
	4, // 3: api.OrderService.CreateOrder:input_type -> api.CreateOrderCommand
	1, // 4: api.OrderService.GetOrder:input_type -> api.GetOrderQuery
	5, // 5: api.OrderService.CreateOrder:output_type -> api.CreateOrderResult
	2, // 6: api.OrderService.GetOrder:output_type -> api.GetOrderResult
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_orders_proto_init() }
func file_api_orders_proto_init() {
	if File_api_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_orders_proto_rawDesc), len(file_api_orders_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_orders_proto_goTypes,
		DependencyIndexes: file_api_orders_proto_depIdxs,
		EnumInfos:         file_api_orders_proto_enumTypes,
		MessageInfos:      file_api_orders_proto_msgTypes,
	}.Build()
	File_api_orders_proto = out.File
	file_api_orders_proto_goTypes = nil
	file_api_orders_proto_depIdxs = nil
}
